/**
 * This file was generated by howl-cli (@maarkllc/code-config)
 */
module.exports = {
  extends: ['./node_modules/@maarkllc/code-config/configs/eslint/{config}'],
  rules: {
    // Overwrite rules here
  }
}
