/**
 * This file was generated by code-config CLI (@maarkllc/code-config)
 */
module.exports = {
  extends: ['./node_modules/@maarkllc/code-config/configs/eslint/{config}'],
  rules: {
    // Overwrite rules here
  },
}
