/**
 * This file was generated by code-config CLI (@maarkllc/code-config)
 */
import ESLintConfig from './node_modules/@maarkllc/code-config/configs/eslint/{config}'

export default [
  ...ESLintConfig,
  {
    rules: {
      // Add custom rules here
    },
  },
]
